### ISSUE TITLE
SQL不全

### ISSUE THREAD

**Issue by xiaoCong2014** [Frank17/ChatOnline#5]
报错 java.sql.SQLSyntaxErrorException: Table 'dbchatroom.viewusertochat' doesn't exist
少了几张的表，比如 CHATUSER，ViewUserToChat 表
你查看一下，com/chatroom/dbhelper/UserHelper.java 里面的SQL语句涉及到的表格是否都有，还有需要填充哪些数据

**Comment by zipzou** [comment]
我重新检查了一下，数据库的表名应为ChatUser，不需要其他表。相应的SQL语句已经更新。

**Comment by widebear** [comment]
ViewUserToChat 创建这个视图SQL 脚本没有提供。

**Comment by zipzou** [comment]
ViewUserToChat这个视图本是用于其他数据库的扩展，现SQL已更新，可尝试使用新SQL进行尝试。若仍出错，可将UserHelper类中与视图ViewUserToChat相关的业务操作删除，即可成功
